# Generated by Django 3.2.14 on 2022-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('friendly_name', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=100)),
                ('article_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
