name: Lighthouse
on:
    push:
        branches: [main]
    pull_requests:
        branches: [main]

jobs:
    lighthouse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - run: mkdir ${{ github.workspace }}/tmp/artifacts
            - name: Lighthouse
              uses: foo-software/lighthouse-check-action@master
              with:
                  outputDirectory: ${{ github.workspace }}/tmp/artifacts
                  urls: "https://scott-blogfolio.herokuapp.com/"
            - name: Upload artifacts
              uses: actions/upload-artifact@master
              with:
                  name: Lighthouse reports
                  path: ${{ github.workspace }}/tmp/artifacts
