name: "Deploy docker container to Heroku"
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build, Push and Deploy to Heroku
              id: heroku
              uses: Techmmunity/docker-heroku-deploy@v1.0.0
              with:
                  email: ${{ secrets.HEROKU_EMAIL }}
                  api_key: ${{ secrets.HEROKU_API_KEY }}
                  app_name: ${{ secrets.HEROKU_APP_NAME }}
                  # dockerfile_path: "." # OPTIONAL: set the path to the folder wher the Dockerfile is located, the default is the rootDir
                  # dockerfile_name: "." # OPTIONAL: Custom name to your dockerfile, like Dockerfile.dev
                  # options: "" # OPTIONAL: Docker Build Options
                  # formation: "web" # OPTIONAL: Docker Dyno Formation. By default is web
